# Generated by Django 5.1.15 on 2026-02-19 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0043_remove_projectmember_allocated_task_and_more"),
        ("tasks", "0063_remove_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="allocated_to",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="my_task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="TaskAssignment",
        ),
    ]
