# Generated by Django 5.1.15 on 2026-02-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0042_alter_role_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmember",
            name="allocated_task",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="allocation_ratio",
        ),
    ]
