# Generated by Django 5.1.15 on 2026-02-10 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0028_add_localfiles_parent_storage_index_async'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfilesimportstorage',
            name='parent_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_storage', to='io_storages.workspacelocalfilesimportstorage'),
        ),
    ]
